# Generated by Django 4.2.16 on 2026-05-22 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('mode', models.CharField(choices=[('in_person', 'In-Person'), ('phone', 'Phone Call'), ('video', 'Video Call')], default='video', max_length=20)),
                ('round_type', models.CharField(choices=[('screening', 'Screening'), ('technical', 'Technical Round'), ('hr', 'HR Round'), ('final', 'Final Round'), ('other', 'Other')], default='screening', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location or video meeting link', max_length=300)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
    ]
